# Generated by Django 3.0.6 on 2020-05-17 15:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vaga',
            name='data_entrada',
        ),
        migrations.RemoveField(
            model_name='vaga',
            name='data_saida',
        ),
        migrations.AddField(
            model_name='vaga',
            name='ocupada',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='LogDeEstacionamento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_entrada', models.DateField(blank=True, null=True)),
                ('data_saida', models.DateField(blank=True, null=True)),
                ('area', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.Area')),
                ('veiculo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.Veiculo')),
            ],
        ),
    ]
