# Generated by Django 3.0.6 on 2020-05-17 11:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pessoa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
            ],
        ),
        migrations.AlterField(
            model_name='area',
            name='capacidade',
            field=models.IntegerField(),
        ),
        migrations.CreateModel(
            name='Funcionario',
            fields=[
                ('pessoa_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='app.Pessoa')),
                ('matricula', models.CharField(max_length=15)),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            bases=('app.pessoa',),
        ),
        migrations.CreateModel(
            name='Proprietario',
            fields=[
                ('pessoa_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='app.Pessoa')),
                ('tipo', models.IntegerField(choices=[(0, 'ALUNO'), (1, 'PROFESSORES'), (2, 'ADMINISTRATIVO'), (3, 'VISITANTES')])),
            ],
            bases=('app.pessoa',),
        ),
        migrations.CreateModel(
            name='Ocorrencia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.IntegerField(choices=[(0, 'FURTO'), (1, 'SINISTRO'), (2, 'ESTACIONAMENTO INDEVIDO'), (3, 'AVARIA'), (4, 'INUNDAÇÃO'), (5, 'OUTROS')])),
                ('data_ocorrencia', models.DateField(blank=True, null=True)),
                ('data_registro', models.DateField(auto_now=True)),
                ('funcionario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.Funcionario')),
            ],
        ),
    ]
